services:
  - type: web
    name: chirper-web
    env: ruby
    plan: free
    numInstances: 1
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/deploy/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chirper-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: chirper-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  - type: redis
    name: chirper-redis
    maxmemoryPolicy: noeviction
    ipAllowList: []

  - type: worker
    name: chirper-sidekiq
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: chirper-db
    plan: free
    postgresMajorVersion: 14
